Website/Models/AboutUsViewModel.cs
using DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Website.Models
{
    public class AboutUsViewModel
    {
        public string Title { get; set; }

        public IEnumerable<Employee> EmployeeList { get; set; }
    }
}

Website/Controllers/AboutUsController.cs
using System.Web.Mvc;
using DataAccess.Models;
using DataAccess.Services;
using Website.Models;

namespace Website.Controllers
{
    public class AboutUsController : Controller
    {
        private IEmployeeData _db;

        public AboutUsController(IEmployeeData db)
        {
            this._db = db;
        }

        public ActionResult Index()
        {
            var model = new AboutUsViewModel();

            model.EmployeeList = _db.GetAll();
            model.Title = "Employees";

            return View(model);
        }
    }
}

Website/Controllers/AdditionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class AdditionalController : Controller
    {
        // GET: Additional
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrivacyPolicy()
        {
            return View();
        }

        public ActionResult NotFoundPage()
        {
            return View();
        }
    }
}

Website/Controllers/AdminController.cs
using DataAccess.Models;
using DataAccess.Services;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class AdminController : Controller
    {
        private IEmployeeData _db;
        public AdminController(IEmployeeData db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_db.GetAll());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _db.Add(employee);

                return RedirectToAction("Details", new { id = employee.ID });
            }

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _db.Update(employee);
                TempData["Message"] = "You have saved the employee !";

                return RedirectToAction("Details", new { id = employee.ID });
            }

            return View();
        }

        public ActionResult Details(int id)
        {
            var model = _db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var model = _db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection form)
        {
            _db.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

Website/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Website/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class PortfolioController : Controller
    {
        // GET: Portfolio
        public ActionResult Index()
        {
            return View();
        }
    }
}

Website/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            return View();
        }
    }
}

Website/Views/AboutUs/Index.cshtml
@model Website.Models.AboutUsViewModel

<section class="title">
    <div class="container">
        <div class="row-fluid">
            <div class="span6">
                <h1>About Us</h1>
            </div>
            <div class="span6">
                <ul class="breadcrumb pull-right">
                    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
                    <li class="active">About Us</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- / .title -->

@Html.Partial("_AboutUsEmployees", Model.EmployeeList)

<!--Bottom-->
<section id="bottom" class="main">
    <!--Container-->
    <div class="container">
        <!--row-fluids-->
        <div class="row-fluid">
            <!--Contact Info-->
            <div class="span3">
                <h4>CONTACT US</h4>
                <ul class="unstyled address">
                    <li>
                        <i class="icon-home"></i><strong>Address:</strong> Carrera 7 # 72-01<br>Bogotá D.C., Colombia
                    </li>
                    <li>
                        <i class="icon-envelope"></i>
                        <strong>Email: </strong> <a href="mailto:company@domain.com">company@domain.com</a>
                    </li>
                    <li>
                        <i class="icon-globe"></i>
                        <strong>Website:</strong> <a href="http://www.domain.com">www.domain.com</a>
                    </li>
                    <li>
                        <i class="icon-phone"></i>
                        <strong>Telephone:</strong> 123-456-7890
                    </li>
                </ul>
            </div>
            <!--End Contact Info-->
            <!--Important Links-->
            <div id="tweets" class="span3">
                <h4>COMPANY NAME</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Erro 404</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <!--Important Links-->
            <div id="archives" class="span2">
                <h4>ARCHIVES</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">Link No. 1</a></li>
                        <li><a href="#">Link No. 2</a></li>
                        <li><a href="#">Link No. 3</a></li>
                        <li><a href="#">Link No. 4</a></li>
                        <li><a href="#">Link No. 5</a></li>
                        <li><a href="#">Link No. 6</a></li>
                    </ul>
                </div>
            </div>
            <!--End Links-->
            <div class="span4">
                <h4>FACEBOOK</h4>
                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=340&height=130&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false&appId" width="340" height="130" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
            </div>
        </div>
        <!--/row-fluid-->
    </div>
    <!--/container-->
</section>
<!--/bottom-->

Website/Views/AboutUs/_AboutUsEmployees.cshtml
@model  IEnumerable<DataAccess.Models.Employee>

<section id="about-us" class="container main">
    <div class="row-fluid">
        <div class="span6">
            <h3>Nullam Interdum Aliquet</h3>
            <p>Aliquam vehicula augue sed felis tempor, ac interdum lorem sodales. Proin dictum imperdiet est, et sodales tellus consequat sit amet. Vestibulum ullamcorper felis non magna rutrum, ornare finibus erat varius. Morbi vulputate metus purus, ut dignissim ex commodo in. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras tempor laoreet felis, ut scelerisque purus sagittis eu. Cras nec pharetra ipsum. Suspendisse commodo neque massa, ut posuere massa lobortis sed. Aenean semper dui at ex rhoncus, in rhoncus nisl tincidunt.</p>
        </div>
        <div class="span6">
            <h3>Praesent Scelerisque</h3>
            <div class="accordion" id="accordion2">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                            Donec Accumsan Dui
                        </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                        <div class="accordion-inner">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget scelerisque diam. Donec accumsan dui metus, ac ultricies elit ullamcorper non. Aenean finibus massa et erat vestibulum, nec condimentum massa aliquet. Ut suscipit nisi nec lorem placerat congue. Sed maximus sapien leo, non aliquet lacus porta eu. Proin mattis sem at leo accumsan, at porta mauris pharetra. Praesent rhoncus purus nec arcu imperdiet, ac rhoncus libero fringilla.
                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                            Ultricies Elit
                        </a>
                    </div>
                    <div id="collapseTwo" class="accordion-body collapse">
                        <div class="accordion-inner">
                            Vivamus posuere lectus vel lectus varius iaculis. Pellentesque diam ligula, volutpat vel tortor non, consectetur condimentum magna. Sed vitae sapien tincidunt, rutrum ipsum vitae, mattis justo. Phasellus vel arcu mi. In hac habitasse platea dictumst. Pellentesque sed felis velit. Nunc id fermentum est. Proin lacinia tempus tincidunt. Ut massa sem, volutpat ut vehicula in, pellentesque et velit. Quisque ac varius orci, a vulputate purus. Etiam scelerisque in sapien nec sollicitudin.
                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                            Suscipit Nisi Nec
                        </a>
                    </div>
                    <div id="collapseThree" class="accordion-body collapse">
                        <div class="accordion-inner">
                            Nullam erat ex, placerat in ligula nec, vestibulum elementum turpis. Proin rutrum nisi vitae hendrerit pretium. Donec eu elit diam. Sed fermentum aliquam ex, eget viverra libero posuere non. Suspendisse mattis varius convallis. Donec eget blandit sapien, et tristique tortor. Cras tempus, mi vitae feugiat feugiat, ante ex ornare neque, sed facilisis magna erat at lorem. Nunc et congue velit, quis aliquam turpis. Nam porta luctus neque et luctus. Cras dapibus, nisl eget sodales pharetra, dui dui pulvinar diam, sed maximus orci quam non eros.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row-fluid">
        <div class="span6">
            <h2>Nunc vestibulum</h2>
            <div>
                <div class="progress"><div class="bar" style="width: 80%; text-align:left; padding-left:10px;">Suspendisse</div></div>
                <div class="progress progress-warning"><div class="bar" style="width: 70%; text-align:left; padding-left:10px;">Nulla tempor</div></div>
                <div class="progress progress-info"><div class="bar" style="width: 60%; text-align:left; padding-left:10px;">Vivamus</div></div>
                <div class="progress progress-danger"><div class="bar" style="width: 90%; text-align:left; padding-left:10px;">Pellentesque</div></div>
            </div>
        </div>
        <div class="span6">
            <h2>Proin tortor tellus</h2>
            <p>Mauris sapien purus, commodo at augue id, ornare venenatis risus. Sed et nibh sit amet quam facilisis sodales. Suspendisse consequat pellentesque suscipit. In vel scelerisque velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean a lorem posuere tortor fermentum bibendum sed ut elit. Praesent suscipit, metus sit amet rhoncus dignissim, nisl ipsum vestibulum sem, ut rutrum lacus felis porttitor velit. Suspendisse elementum, leo vitae maximus feugiat, libero arcu fermentum eros, ut tincidunt mi felis at ipsum. Fusce cursus, lacus ac pellentesque mollis, leo massa iaculis sem, ut egestas velit eros id sapien. Vestibulum ultrices convallis dapibus. Suspendisse libero tellus, interdum eu sodales ac.</p>
        </div>
    </div>
    <hr>
    <!-- Company team -->
    <h1 class="center">Company Team</h1>
    <hr>
    <div class="row-fluid">
        <div class="span3">
            <div class="box">
                <p><img src="images/sample/team1.jpg" alt=""></p>
                <h5>John Smith</h5>
                <p>Nullam ornare, odio eu lacinia venenatis, dui purus varius odio, in pellentesque purus nibh in libero. Nullam magna felis.</p>
                <a class="btn btn-social btn-facebook" href="#"><i class="icon-facebook"></i></a> <a class="btn btn-social btn-google-plus" href="#"><i class="icon-google-plus"></i></a> <a class="btn btn-social btn-twitter" href="#"><i class="icon-twitter"></i></a> <a class="btn btn-social btn-linkedin" href="#"><i class="icon-linkedin"></i></a>
            </div>
        </div>
        <div class="span3">
            <div class="box">
                <p><img src="images/sample/team2.jpg" alt=""></p>
                <h5>Alice Schulth</h5>
                <p>Nullam ornare, odio eu lacinia venenatis, dui purus varius odio, in pellentesque purus nibh in libero. Nullam magna felis.</p>
                <a class="btn btn-social btn-facebook" href="#"><i class="icon-facebook"></i></a> <a class="btn btn-social btn-google-plus" href="#"><i class="icon-google-plus"></i></a> <a class="btn btn-social btn-twitter" href="#"><i class="icon-twitter"></i></a> <a class="btn btn-social btn-linkedin" href="#"><i class="icon-linkedin"></i></a>
            </div>
        </div>
        <div class="span3">
            <div class="box">
                <p><img src="images/sample/team3.jpg" alt=""></p>
                <h5>Helen Cooper</h5>
                <p>Nullam ornare, odio eu lacinia venenatis, dui purus varius odio, in pellentesque purus nibh in libero. Nullam magna felis.</p>
                <a class="btn btn-social btn-facebook" href="#"><i class="icon-facebook"></i></a> <a class="btn btn-social btn-google-plus" href="#"><i class="icon-google-plus"></i></a> <a class="btn btn-social btn-twitter" href="#"><i class="icon-twitter"></i></a> <a class="btn btn-social btn-linkedin" href="#"><i class="icon-linkedin"></i></a>
            </div>
        </div>
        <div class="span3">
            <div class="box">
                <p><img src="images/sample/team4.jpg" alt=""></p>
                <h5>Charles Hester</h5>
                <p>Nullam ornare, odio eu lacinia venenatis, dui purus varius odio, in pellentesque purus nibh in libero. Nullam magna felis.</p>
                <a class="btn btn-social btn-facebook" href="#"><i class="icon-facebook"></i></a> <a class="btn btn-social btn-google-plus" href="#"><i class="icon-google-plus"></i></a> <a class="btn btn-social btn-twitter" href="#"><i class="icon-twitter"></i></a> <a class="btn btn-social btn-linkedin" href="#"><i class="icon-linkedin"></i></a>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
</section>

Website/Views/Additional/NotFoundPage.cshtml
<!-- 404 error -->
<section id="error" class="container">
    <h1>404, Page not found</h1>
    <p>The Page you are looking for doesn't exist or an other error occurred.</p>
    <a class="btn btn-success" href="/">GO BACK TO THE HOMEPAGE</a>
</section>
<!-- /404 error -->
<!--Bottom-->
<section id="bottom" class="main">
    <!--Container-->
    <div class="container">
        <!--row-fluids-->
        <div class="row-fluid">
            <!--Contact Info-->
            <div class="span3">
                <h4>CONTACT US</h4>
                <ul class="unstyled address">
                    <li>
                        <i class="icon-home"></i><strong>Address:</strong> Carrera 7 # 72-01<br>Bogotá D.C., Colombia
                    </li>
                    <li>
                        <i class="icon-envelope"></i>
                        <strong>Email: </strong> <a href="mailto:company@domain.com">company@domain.com</a>
                    </li>
                    <li>
                        <i class="icon-globe"></i>
                        <strong>Website:</strong> <a href="http://www.domain.com">www.domain.com</a>
                    </li>
                    <li>
                        <i class="icon-phone"></i>
                        <strong>Telephone:</strong> 123-456-7890
                    </li>
                </ul>
            </div>
            <!--End Contact Info-->
            <!--Important Links-->
            <div id="tweets" class="span3">
                <h4>COMPANY NAME</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Erro 404</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <!--Important Links-->
            <div id="archives" class="span2">
                <h4>ARCHIVES</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">Link No. 1</a></li>
                        <li><a href="#">Link No. 2</a></li>
                        <li><a href="#">Link No. 3</a></li>
                        <li><a href="#">Link No. 4</a></li>
                        <li><a href="#">Link No. 5</a></li>
                        <li><a href="#">Link No. 6</a></li>
                    </ul>
                </div>
            </div>
            <!--End Links-->
            <div class="span4">
                <h4>FACEBOOK</h4>
                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=340&height=130&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false&appId" width="340" height="130" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
            </div>
        </div>
        <!--/row-fluid-->
    </div>
    <!--/container-->
</section>
<!--/bottom-->

Website/Views/Admin/Create.cshtml
@model DataAccess.Models.Employee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="container main">
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Intro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Intro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Intro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SocialMediaID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SocialMediaID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SocialMediaID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</section>

Website/Views/Admin/Details.cshtml
@model DataAccess.Models.Employee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="container main">
    <h2>Details</h2>

    <div>
        <h4>Employee</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Picture)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Picture)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Intro)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Intro)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SocialMediaID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SocialMediaID)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</section>

Website/Views/Admin/Index.cshtml
@model IEnumerable<DataAccess.Models.Employee>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="container main">

    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New Employee", "Create", "Admin")
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Intro)
            </th>
            <th>
                <p>Social media</p>
            </th>
            <th>
                <p>Operations</p>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            string imagePath = string.Concat("~/", item.Picture);
            <tr>
                <td>
                    <img src=@Url.Content(imagePath) />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Intro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SocialMediaID)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</section>

Website/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_HomeSlider")

@Html.Partial("_HomeMainInfo")

@Html.Partial("_HomeServices")

@Html.Partial("_HomeRecentWorks")

@Html.Partial("_HomeClients")

@Html.Partial("_HomeBottom")


@section scripts
{
    <script type="text/javascript">
        $(function () {
            var Page = (function () {
                var $navArrows = $('#nav-arrows'),
                    slitslider = $('#slider').slitslider({
                        autoplay: true
                    }),
                    init = function () {
                        initEvents();
                    },
                    initEvents = function () {
                        $navArrows.children(':last').on('click', function () {
                            slitslider.next();
                            return false;
                        });
                        $navArrows.children(':first').on('click', function () {
                            slitslider.previous();
                            return false;
                        });
                    };
                return { init: init };
            })();

            Page.init();
        });
    </script>
}

Website/Views/Home/_HomeMainInfo.cshtml
<section class="main-info">
    <div class="container">
        <div class="row-fluid">
            <div class="span9">
                <h4>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos</h4>
                <p class="no-margin">Ut ultrices eu nunc vitae scelerisque. Praesent sollicitudin accumsan diam, sed tristique diam sodales ut. Ut volutpat tempor dignissim.</p>
            </div>
            <div class="span3">
                <a class="btn btn-success btn-large pull-right" href="#">Nulla ornare varius</a>
            </div>
        </div>
    </div>
</section>

Website/Views/Shared/_Header.cshtml
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a id="logo" class="pull-left" href="/"></a>
            <div class="nav-collapse collapse pull-right">
                <ul class="nav">
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Services", "Index", "Services")</li>
                    <li>@Html.ActionLink("Portfolio", "Index", "Portfolio")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Additional<i class="icon-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("404", "NotFoundPage", "Additional")</li>
                            <li>@Html.ActionLink("Privacy policy", "PrivacyPolicy", "Additional")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact", "Index", "ContactUs")</li>
                </ul>
            </div>
        </div>
    </div>
</header>

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Header")
    
    @RenderBody()
    
    @Html.Partial("_Footer")


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/otherScripts")
    @RenderSection("scripts", required: false)
</body>
</html>